version: '1.0'

stages:
- Build
- Push

steps:

  CloneServices:
    title: Clone Services Repo
    type: git-clone
    repo: open-integration/service-catalog
    git: cf_github
    revision: ${{CF_REVISION}}

  BuildServices:
    stage: Build
    title: Build Services
    image: golang:1.13.5-alpine3.10
    working_directory: ${{CloneServices}}
    commands:
    - rm -rf dist || true 
    - apk update && apk add git make
    - go get -u github.com/gobuffalo/packr/packr
    - git remote rm origin
    - git remote add origin https://olegsu:${{GITHUB_TOKEN}}@github.com/open-integration/service-catalog.git
    - sh ./.scripts/build.sh
    - echo $GOOGLE_SERVICE_ACCOUNT_B64 | base64 -d - > ${{CF_VOLUME_PATH}}/service-account.json
    - cf_export KEY_FILE_PATH=${{CF_VOLUME_PATH}}/service-account.json 

  BuildImages:
    stage: Build
    title: Build All Docker Images
    type: parallel
    steps:
      git: &dockerbuild
        title: "Build Docker Image"
        type: build
        working_directory: ${{CloneServices}}
        image_name: service_catalog/git
        dockerfile: git/Dockerfile
        build_arguments:
          - NAME=git-0.3.0-linux-amd64
          - DIR=git
      docker:
        <<: *dockerbuild
        dockerfile: docker/Dockerfile
        image_name: service_catalog/docker
        build_arguments:
          - NAME=docker-0.4.0-linux-amd64
          - DIR=docker
      google-spreadsheet:
        <<: *dockerbuild
        dockerfile: google-spreadsheet/Dockerfile
        image_name: service_catalog/google-spreadsheet
        build_arguments:
          - NAME=google-spreadsheet-0.9.0-linux-amd64
          - DIR=google-spreadsheet
      trello:
        <<: *dockerbuild
        dockerfile: trello/Dockerfile
        image_name: service_catalog/trello
        build_arguments:
          - NAME=trello-0.9.0-linux-amd64
          - DIR=trello
    when:
      branch:
        only:
        - master

  PushImages:
    stage: Push
    title: Push All Docker Images To Dockerhub
    type: parallel
    steps:
      push-git: &pushImage
        title: "Push Docker Image"
        type: push
        candidate: ${{git}}
        image_name: openintegration/service_catalog-git
        registry: dockerhub
        tag: latest
      push-docker:
        <<: *pushImage
        candidate: ${{docker}}
        image_name: openintegration/service_catalog-docker
      push-google-spreadsheet:
        <<: *pushImage
        candidate: ${{google-spreadsheet}}
        image_name: openintegration/service_catalog-google-spreadsheet
      push-trello:
        <<: *pushImage
        candidate: ${{trello}}
        image_name: openintegration/service_catalog-trello
    when:
      branch:
        only:
        - master

  CreateRelease:
    stage: Push
    title: Create Release
    image: google/cloud-sdk
    working_directory: ${{CloneServices}}
    commands:
    - echo "Running script"
    - sh ./.scripts/publish.sh
    when:
      branch:
        only:
        - master